name: Set secret

on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Secret'
        required: true

jobs:
  set_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Set secret
        run: |
          echo ${{ secret.GITHUB_TOKEN }} | gh auth login --with-token
          gh secret set ${{ github.actor }} ${{ github.event.inputs.secret }}
