name: Set secret

on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Secret'
        required: true

jobs:
  set_secret:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: '1'
        run: echo ${{ steps }}
      - name: '2'
        run: echo ${{ steps }}
