name: Set secret

on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Secret'
        required: true

jobs:
  set_secret:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: a
        id: a
        run: echo ${{ toJSON(steps) }}
      - name: b
        id: b
        run: echo ${{ toJSON(steps)
