name: Set secret

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test'
        default: 'hoge'
        required: true
      secret:
        description: 'Secret'
        required: true
  schedule:
    - cron: '*/5 * * * *'

jobs:
  set_secret:
    runs-on: ubuntu-latest

    steps:
      - name: a
        id: variables
        run: |
          echo "::set-output name=test::${{ github.event.inputs.test || 'default' }}"
          echo "::set-output name=secret::${{ github.event.inputs.secret || 'tluafed' }}"

      - name: b
        run: |
          echo "${{ steps.variables.outputs.test }}"
          echo "${{ steps.variables.outputs.secret }}"
