name: Set secret

on:
  workflow_dispatch:
    inputs:
      secret:
        description: 'Secret'
        required: true

jobs:
  set_secret:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: a
        id: a
        run: exit 1
      - name: b
        if: failure()
        run: echo "${{ toJSON(steps) }}"
